server:
  port: 3000

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.auth0.example: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: 56H75cnFg8B5ssCbkhKnsiMAtZ1xFGCp
            client-secret: tlcejHi3EYSY5LychFBI4Qp8i5APmf-DQyDSAE44g5E7zA4gNAksSM9GbY5TQuP2
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-3zoo7p4k.us.auth0.com/
